service: weave-ws
provider:
  name: aws
  runtime: nodejs14.x
plugins:
  - serverless-webpack
  - serverless-webpack-prisma
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
package:
  artifact: .build/serverless/weave-ws.zip
  patterns:
    - "!node_modules/.prisma/client/libquery_engine-*"
    - "node_modules/.prisma/client/libquery_engine-rhel-*"
    - "!node_modules/prisma/libquery_engine-*"
    - "!node_modules/@prisma/engines/**"

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      forceInclude:
        - ws
functions:
  connect:
    handler: src/functions/connect.connect
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: src/functions/disconnect.disconnect
    events:
      - websocket:
          route: $disconnect
  default:
    handler: src/functions/default.default
    events:
      - websocket:
          route: $default
